### ISSUE TITLE
SEVIRI L1b netCDF reader not dask-compliant

### ISSUE THREAD

**Issue by sjoro** [pytroll/satpy#1075]
`seviri_l1b_nc`-reader is not using `dask`, i.e. `get_dataset`-method returns a plain `xarray.Dataset`-object.

The reader should be "daskified", which may have an impact on `SEVIRICalibrationHandler` in `seviri_base.py` and other readers that use this class.

**Comment by BENR0** [comment]
Not directly related to dask but when working on the reader the following should probably be changed too. I noticed that the nc reader uses `mask_and_scale=False` while opening the dataset. These attribute (among others) are not removed from the dataset and therefore lead to what I think are unwanted results when writing out data with the cf writer. I think some of the attributes of the original file should be stripped (or updated) because they don't make sense later on, or are confusing (e.g. comment, long_name, nc_key, valid_min, valid_max, etc.).
