### ISSUE TITLE
`find_files_and_readers` read unneeded files

### ISSUE THREAD

**Issue by mraspaud** [pytroll/satpy#1099]
> you might need to indicate a time also in `find_files_and_readers` to load just one set of files at the time.

I found it better to separate my favorite files in another directory, instead of indicating the time range. Because `find_files_and_readers` seems to read all the files, whether or not being indicated in the time range.

_Originally posted by @anikfal in https://github.com/pytroll/satpy/issues/1087#issuecomment-591959947_

**Comment by anikfal** [comment]
I do not think if `find_files_and_readers` ignores start and end times. Rather, it cannot efficiently apply the time range.
For example, suppose we have 100 files and we want to plot only 4 of them. Instead of reading and plotting exactly those 4 files, `find_files_and_readers` takes considerable time to read (not plot) all of the 100 files for plotting those 4 specific files. Therefore, it wastes time in reading 96 extra files.

**Comment by mraspaud** [comment]
Thanks for the clarification.

**Comment by anikfal** [comment]
I no longer see this problem in Satpy version 0.33.1. `find_files_and_readers` exactly reads only those files in the time range.

**Comment by djhoese** [comment]
Thanks for the update @anikfal!
