### ISSUE TITLE
MERSI-2 250meters corrected refl.

### ISSUE THREAD

**Issue by jee34** [pytroll/satpy#1154]
Hi, i am new to write here on Github.
Satpy is fantastic, works well.
Ok here is the thing:
Mersi-2 true color is available with Rayleigh and correcred reflectance for 1000m resolution only because SZA data is only available in the 1000m resolution HDF file.
Is it possible to use the 1000m SZA data with the 1000m hdf file and interpolate it to 250m?
That way, it would be possible to create a 250m resolution picture with true color and including corrected reflectance and Rayleigh correction.  Thank you.

**Comment by djhoese** [comment]
The MERSI-2 reader allows for datasets to be loaded at whatever resolution you provide. So if you only provide 1000m input files then that's the only resolution available. If you also provide 250m resolution files then the 250m versions of the datasets will be loaded by default (default is to load the highest quality resolution possible). As you've pointed out the SZA data is only available at 1000m resolution, but there is a simple way around that in Satpy: the `native` resampler. For example:

```
scn = Scene(reader='mersi2_l1b', filenames=[...])
scn.load(['true_color'])
new_scn = scn.resample(resampler='native')
new_scn.save_datasets()
```

This will create a 250m resolution true_color composite (*if* you provided the 250m and 1000m resolution files). Initially when you try to `load` the `true_color` you will likely see a warning logged saying something like "you need to resample to generate this composite". This is because Satpy is trying to combine bands 1, 2, and 3 at 250m resolution with SZA at 1000m resolution. The `native` resampler, by default, will replicate pixels of the SZA to make them 250m resolution. After resampling Satpy automatically re-attempts to create the `true_color` composite and should succeed. It can then be saved to disk using `save_datasets`.

Typically the `native` resampler isn't needed for MERSI-2 because it is polar-orbiting and is typically resampled to a uniform grid (`AreaDefinition`). This resampling serves the same purpose here where every input dataset will now be at the same resolution (the resolution of the grid being resampled to).

Hopefully this answers your question. If you aren't able to get this to work please post an example of what you are trying to do and we can go from there.

**Comment by jee34** [comment]
Thanks! It worked right away. My error was that with "scn.load" i added the argument "resolution=250"

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by djhoese** [comment]
Glad it worked for you. And yeah that's an easy "gotcha" to run in to when doing stuff like this.
