### ISSUE TITLE
Saving true color GOES image requires double-resampling if calibration='radiance'

### ISSUE THREAD

**Issue by simonrp84** [pytroll/satpy#1258]
**Describe the bug**
If I wish to save a GOES `true_color_nocorr` composite with radiance calibration then I need to resample the data twice, which should not be the case. This may also happen with other satellites or composites too.

**To Reproduce**

```python
# curfiles is a list of the required GOES-ABI datafiles
scn = Scene(curfiles, reader='abi_l1b')
scn.load(['true_color_nocorr', 'C04'], calibration='radiance')
scn2 = scn.resample(scn.min_area(), resampler='native')
scn2.save_datasets()
```

**Expected behavior**
A channel 04 and true_color_nocorr dataset are saved to disk with appropriate filenames. I expect to see the following output on screen:
```
The following datasets were not created and may require resampling to be generated: DatasetID(name='true_color_nocorr', wavelength=None, resolution=None, polarization=None, calibration='radiance', level=None, modifiers=None)
```

**Actual results**
Only the C04 file is produced, true_color_nocorr is not produced and I see this message in addition to the one above:
```
The following datasets were not created: DatasetID(name='true_color_nocorr', wavelength=None, resolution=None, polarization=None, calibration='radiance', level=None, modifiers=None)
```

If, however, I change my code to this:
```scn.load(['true_color_nocorr', 'C04'], calibration='radiance')
scn2 = scn.resample(scn.min_area(), resampler='native')
scn2 = scn.resample(scn.min_area(), resampler='native')
scn2.save_datasets()
```
Then it works fine. If I instead remove `calibration='radiance'` from the load call then I only need one `resample` call.

**Environment Info:**
Windows 10
Satpy 0.22.0
Pyresample 1.16.0

**Comment by djhoese** [comment]
What is the definition for this `true_color_nocorr`? The only thing I can see calling resample twice (the way you've done it) doing is pre-filling the resampling cache. It should behave exactly the same. I *could* see the composite *never* being generated because of the calibration, but you say the double resample fixes that so :shrug:

**Comment by simonrp84** [comment]
@djhoese It's defined here: https://github.com/pytroll/satpy/blob/master/satpy/etc/composites/abi.yaml#L110

Anyway, the same happens with the `true_color` composite:
```
scn.load(['true_color'], calibration='radiance')
scn2 = scn.resample(scn.min_area(), resampler='native')
scn2.save_datasets()
```
Results in:
`RuntimeError: None of the requested datasets have been generated or could not be loaded. Requested composite inputs may need to have matching dimensions (eg. through resampling).`

**Comment by djhoese** [comment]
While I agree this is buggy, I'm curious what you were hoping to get as an end result in your original call?

**Comment by simonrp84** [comment]
Sorry, I don't understand what you mean. I expected an image to be successfully output, as occurs if I call `resample` twice.

**Comment by djhoese** [comment]
I mean you are specifying `calibration='radiance'` but are generating a traditionally reflectance-only RGB.

**Comment by simonrp84** [comment]
The specific scene I'm looking at is at a very high solar zenith angle, so with reflectances the `true_color` scene gets saturated.

Also, in general for algorithm development I prefer working as close to the satellite data as possible, hence don't usually want to apply radiance -> reflectance conversions.

**Comment by djhoese** [comment]
Ok I think I've figured this out. I'll try to keep this abstract and understandable:

1. You load true_color_nocorr and specify a blanket request of "use calibration='radiance'".
2. Satpy loads the true color definition and then tries to find its dependencies.
3. When Satpy looks for green_nocorr, it knows about green_nocorr but not anything as specific as "calibration='radiance'". So as a placeholder it says "we'll load something called green_nocorr and say it has a calibration of radiance for now".
4. Satpy will fail to generate all the dependencies because of differing resolutions.
5. After you resample, Satpy will create the green_nocorr but it ignores the DatasetID that was originally created for it and instead assumes that the compositor knows best and will create the DatasetID from the generated DataArray's metadata. This results in `calibration=None`.
6. Then we hit the actual bug where true_color_nocorr tries to say "ok we tried to create the composite, let's handle whatever happened" which could be that it is a static image compositor that doesn't need to be loaded, it was loaded and is in the Scene currently, it is a delayed composite due to incompatible areas, it wasn't generated but is optional so that's ok, or it wasn't generated and is a hard requirement so we should fail. This all happens right here:

https://github.com/pytroll/satpy/blob/b72495c81cfa204dbb030e97ae990703119b542f/satpy/scene.py#L748-L758

The bug is that `prereq_id` is the `calibration='radiance'` version of the DatasetID, but during `self._generate_composite` we *update* that Node object so `.name` is now the `calibration=None` version of the DatasetID but `prereq_id` hasn't also been updated.

I'm hesitant to fix this (simply redefine `prereq_id` after `self._generate_composite` due to #1088 by @mraspaud  since this might have a completely different behavior. @mraspaud what do you think?

Side bug: All of the logs/exceptions using `prereq_id` in

https://github.com/pytroll/satpy/blob/b72495c81cfa204dbb030e97ae990703119b542f/satpy/scene.py#L773

are using the last prereq to be analyzed/attempted but that doesn't mean that that was the prereq that caused the delay. For example in this issues use case we are delayed because of green_nocorr, but the log message says we are delayed because of C01 even though that was loaded just fine.

**Comment by mraspaud** [comment]
@djhoese I tackled something similar in #1088 indeed, so I can try to run that case in the PR so how it performs

**Comment by mraspaud** [comment]
@djhoese @simonrp84 I can confirm it works in #1088
