### ISSUE TITLE
scn.load('C01') gives - TypeError

### ISSUE THREAD

**Issue by raybellwaves** [pytroll/satpy#1344]
I know I have to do `scn.load(['C01'])`.

and if do `scn.load('C01')` I get

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-697a49a0eee1> in <module>
----> 1 scn.load('C01')

~/local/bin/anaconda3/envs/dev/lib/python3.8/site-packages/satpy/scene.py in load(self, wishlist, calibration, resolution, polarization, level, generate, unload, **kwargs)
    957         """
    958         if isinstance(wishlist, str):
--> 959             raise TypeError("'load' expects a list of datasets, got a string.")
    960         dataset_keys = set(wishlist)
    961         needed_datasets = (self.wishlist | dataset_keys) - \

TypeError: 'load' expects a list of datasets, got a string.
```

Could you accept a string if the string is in `scn.available_dataset_names()`. i.e. under the hood call a list on the string so it's in the format `scene` likes? `'C01'` -> `['C01']`. No idea if this will mess things up downstream.

In addition, `show` accepts a string `scn.show('C01')`

**Comment by raybellwaves** [comment]
Hmm I guess that wouldn't work for `true_color`

**Comment by djhoese** [comment]
There is `available_composite_names` and you can pass `scn.available_dataset_names(composites=True)`.

My argument for not supporting a single string is that I think we should limit how many inputs we accept. My worry is that if someone is passing a string there may be some other misunderstanding or misuse going on. Rather than producing an odd error later on we decided to produce this direct error. Believe it or not we used to not do this check and you would get an error later on about how Satpy couldn't load datasets `['C', '0', '1']`.

**Comment by raybellwaves** [comment]
Ah interesting. Welcome to close.

**Comment by djhoese** [comment]
Anyone feel free to disagree and provide your ideas. It doesn't have to be this way, but it seemed "safest" to me.
