### ISSUE TITLE
pip install[complete] vs pip install[all]

### ISSUE THREAD

**Issue by raybellwaves** [pytroll/satpy#1350]
In the install instructions it says `pip install satpy[all]`
https://satpy.readthedocs.io/en/latest/install.html#pip-based-installation

I'm used to using `pip install satpy[complete]` e.g. (https://docs.dask.org/en/latest/install.html#pip)

and this seems to get you further that using [all] (in a python3.8 environment:  (https://github.com/pytroll/satpy/pull/1346#issuecomment-687983050

Check (use py 3.7?)
```
$ conda create -n test_env python=3.7
$ conda activate test_env
$ pip install "satpy[all]"
$ conda remove --name test_env --all
$ conda create -n test_env python=3.7
$ conda activate test_env
$ pip install "satpy[complete]"
```

**Comment by djhoese** [comment]
It gets you further because `complete` doesn't actually exist in the `setup.py`. See here for dask: https://github.com/dask/dask/blob/master/setup.py#L29

They have a `complete` extra, we have a `all` extra:

https://github.com/pytroll/satpy/blob/master/setup.py#L79

The bug then in this case is that pip isn't complaining about an extra that doesn't exist.

**Comment by raybellwaves** [comment]
Understood
