### ISSUE TITLE
HSD / HRIT projection question

### ISSUE THREAD

**Issue by Steve-Albers** [pytroll/satpy#1437]
When NetCDF 'hsd' full disk files are written out, the map projection x and y coordinates have units of meters. When reading the HRIT projection documentation, they refer to x and y to be expressed in degrees. I wonder why these are are in different units and how to convert between the two, particularly for Himawari 'hsd' data. Are the CFAC and LFAC variables related to this and what units do these variables use? 

I'm used to seeing GOES NetCDF files on AWS having scaling in radians, and I wonder if the use of meters with the HSD format is different only in being a proportionality constant or is some other type of projection calculation being used.

**Comment by djhoese** [comment]
Just so we're being specific, what do you mean by `NetCDF 'hsd' full disk files`? Do you mean HSD formatted files that are read in by Satpy and then written out using the `cf` writer in Satpy?

Theoretically I think projections can be in any units as long as they work for that coordinate system. There are common units you see like meters and less common units you see like inches or kilometers, but it all depends on the projection. By that I mean, I think it really depends on the geometry of the projection of the Earth and the coordinate system that it uses. This gets pretty complex so we'll ignore it for now unless it helps with understanding AHI's data better.

I don't have a ton of experience with AHI HRIT or the HSD formats, but do have quite a bit of experience with GOES-16/17 ABI L1b. With ABI L1b data you'll see in the NetCDF files that are the official PUG format that the units of the projection are radians or microradians. This was, I believe, part of the original CF standard for defining a geostationary projection in NetCDF files that @mraspaud had a part in establishing. In more recent revisions of CF I don't think having geostationary projection coordinates in radians/microradians is necessary and you'll sometimes also see meters. Due to what the geostationary projection can represent (a disc tangent to the spheroid model of the Earth) it can have these different units. The radians are referring to the viewing angle of the satellite/sensor if I remember correctly. Math...math...math (multiply by the height of the satellite)...you can also have meters to describe these coordinates. I don't see why you couldn't have degrees to also refer to these coordinates as long as it is clear about longitude/latitude degrees versus viewing angle degrees.

The CFAC/LFAC are the "scaling factor" for the column and lines (rows) of the image data. Put another way, these describe the resolution/size of the image pixels in projection space. So if the projection/coordinates are defined in meters, then these factors are in meters ("meters per column"), if radians then radians.

So as far as I know you are right about your meters versus radians comment in your last sentence.

**Comment by mraspaud** [comment]
The x and y in degrees in hrit are related to cfac and lfac in this manner:
x = coff * int(column * cfac * 2**-16)
y = loff * int(line * cfac * 2**-16)

Thats from the cgms document. X and y are called there intermediate coordinates, but are really the viewing angles of the instrument in radians (which is what the goes NC data provides). Multiplying it by the height of the satellite in meters will give you the coordinates of the pixels in the Geos projection, which is what the hsd format has. Going from these coordinates to Lons and lats uses indeed projection formulas. Hope that helps.

**Comment by Steve-Albers** [comment]
Thanks for reading between the lines of my question about reading in HSD full disk files and writing out CF format with `satpy`.  Note that I'm only writing out the files with `satpy` in CF without remapping. I'm simply using `satpy` as a guide to remap the software with another set of software. Nonetheless, I think understanding how `satpy` remaps files may be instructive. 

In the CF files that aren't remapped, written out by `satpy`, I wonder if radians can be written out instead of meters for the X,Y 1D arrays, since this seems to me a more fundamental unit and is the unit used by the GOES ABI CF data seen on in the AWS cloud.

I would ask also if I wanted to remap HSD full disk data with `satpy` what specific values of CFAC and LFAC should be used?

**Comment by mraspaud** [comment]
At the moment, you would have to change the coordinates "by hand" before writing the file to disk in order to have radians, something like
```python
scn['my_channel'].coords['x'] /= satellite_height
scn['my_channel'].coords['y'] /= satellite_height
```
(not tested)
and set the corresponding units to radians.

the CFAC and LFAC shouldn't be needed if you wanted to remap HSD with satpy, but their values should be included in the data itself. You can have a look at the hsd data reader for the details probably.

**Comment by Steve-Albers** [comment]
Thanks for the comments. I now see in this HSD document what some values are for CFAC and LFAC on page 11:

https://www.data.jma.go.jp/mscweb/en/himawari89/space_segment/hsd_sample/HS_D_users_guide_en_v12.pdf

**Comment by mraspaud** [comment]
I'm closing this issue for now as it seems the questions have been answered. Feel free to reopen if this is not the case.
