### ISSUE TITLE
Resampling with bucket resamplers drops coords from xr.DataArray

### ISSUE THREAD

**Issue by BENR0** [pytroll/satpy#1488]
**Describe the bug**
Using bucket resamplers drops the coords from the `xr.DataArray` of the Scene datasets.

**To Reproduce**

```python
scn = Scene(reader="seviri_l1b_nc", filenames=["PATH_TO_SEVIRI_NC_FILE"])
scn.load(["IR_039"])
scn = scn.resample("EuropeCanary", resampler="bucket_avg")
scn["IR_039"].coords

```

**Expected behavior**
The coordinates of the `xr.DataArrays` should be preserved.

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.24.0 and older versions
 - PyResample Version: 1.17.0
 - Readers and writers dependencies (when relevant): [run `from satpy.config import check_satpy; check_satpy()`]

**Comment by djhoese** [comment]
Could you please show what the coordinates are before and what coordinates there are after? Some coordinates are supposed to be overwritten (y/x), others may not be preservable because they are on the y/x dimension. Regardless, this behavior should be the same for **all** resamplers, not just bucket resampling. Could you test with `'nearest'` and see what you get?

**Comment by BENR0** [comment]
The coordinates assigned from the reader are crs, x, y. After the resampling there are no coords at all (xarray prints \*empty\*). Since the example resamples within the same projection I think the coordinates could be be preserved (obviously they are not the same depending on the area definition so preserved is probably the wrong word but they should not be dropped). `'nearest'` preserves the coordinates.

**Comment by djhoese** [comment]
Ah ok. Thanks. This is definitely a bug then. @pnuu The resampler should be able to use the utilities that Satpy has to re-add coordinates. I know the resampler is in pyresample now so this isn't a satpy change. I also know I had to copy the functions over in my EWA PR but since that is not merged yet I'm not sure what you'll have to do.

**Comment by djhoese** [comment]
@pnuu and I have been talking about this on slack (as you've seen @BENR0). It seems the main issue is that there is no call to:

https://github.com/pytroll/satpy/blob/d7e25702d6c1f4cd992def6901f84a18f6be0e55/satpy/resample.py#L311

The reason for this is pretty obvious after @pnuu looked at the commits, the bucket resampling was added a week before the y/x/crs coordinate handling was added (probably parallel pull requests between me and him). If you or @pnuu want to make a pull request adding a call to this function then we can merge it pretty quickly (not sure where it has to be added to make it work for all bucket resamplers).

**Comment by BENR0** [comment]
Ok I will have a look at it and see if I can figure it out even though I am not very familiar with the code.

**Comment by djhoese** [comment]
That would be good. It seems @pnuu won't be able to look at it for a while.
