### ISSUE TITLE
How to calculate area_def for GEOS projection?

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#1731]
I‘m trying to reproject a world map into geos view. I need the lat/lon of boundaries for `coord2area_def.py`, but they are all in space so how can I handle this?

**Comment by djhoese** [comment]
I don't think we have a good way of doing this with the `coord2area_def.py` for the reason you mention. You may want to look at pyresample's `create_area_def` utility function for helping generating an AreaDefinition with some custom parameters: https://pyresample.readthedocs.io/en/latest/geometry_utils.html

However, you'll still probably need to specify things in X/Y meters in the geostationary projection rather than lon/lat degrees...at least if you want the space pixels. The other option would be to load a particular geostationary piece of data (ABI, AHI, etc) and take the AreaDefinition generated by Satpy for those data files.

**Comment by pnuu** [comment]
There are also some built-in area definitions for existing geostationary satellites and some for smaller areas (search for "proj: geos"): https://github.com/pytroll/satpy/blob/main/satpy/etc/areas.yaml

Maybe there's an already suitable in there? Or at least they can be used as a starting point if not.

**Comment by yukaribbba** [comment]
@pnuu @djhoese Thanks guys. I refered to the `area_extent` values in that yaml and successfully produced a new geos by `create_area_def`. The result is good. But when switching algorithm to bilinear, I got some errors. I mentioned it in #1736.
