### ISSUE TITLE
Load composites without file handlers.

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1747]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Composite loading depends on file handles.  If I manually assign datasets to a scene object, I cannot use the scene class to calculate a composite from those datasets.  Toy example:

```
sc = Scene()
sc["flash_extent_density"] = xarray.DataArray(np.arange(100).reshape(10, 10), dims=("y", "x"))
sc["C14"] = xarray.DataArray(np.arange(100).reshape(10, 10), dims=("y", "x"))
sc.load(["C14_flash_extent_density"])
```

Although all dependencies for `C14_flash_extent_density` are available and calculating this composite would not require handling any files, this scene object is not aware of any file handlers and can therefore not calculate this composite.

Real world situations in which this might occur:

- calculating a composite from the result of `MultiScene.blend`, for example, when aggregating `flash_extent_density` from GLM; or
- unit tests in which a developer has assigned synthetic data to a scene and wants to test if a composite is calculated correctly.

**Describe the solution you'd like**

I would like that composite loading does not need a file handler if dependencies are all available.  I'm not sure how exactly it would know what composite to load, but in principle it should be possible for the Scene class to figure out any composites with name `x` for which the dependencies are met.

**Describe any changes to existing user workflow**

Any implementation would need to be careful not to break existing user workflow.

**Additional context**

I don't know if this can be cleanly implemented without refactoring the entire Scene class in the sense of #1469.

The term `load` in this case is somewhat misleading/confusing, because it suggests data are read from storage.  When we "load" a composite, we're not reading anything from storage, we're calculating the composite based on other datasets.

**Comment by djhoese** [comment]
Regarding the `.load` term, under the hood this method is actually calling a "generate" (or maybe its "generate_composites") method which is a little more accurate.

The technical side of this feature request is that the compositor loading code is created during `Scene.__init__`:

https://github.com/pytroll/satpy/blob/f736315178ebeb26a15a48302251cf39534ed143/satpy/scene.py#L113-L116

This comp/mods information is given to the DependencyTree which is used during `.load` to figure out what we have access to and where we can get it from (readers or already in the Scene). Additionally, the comps/mods information depends on what sensors the instantiated Readers represent (ex. `abi_l1b` is `abi`). This let's Satpy find the sensor-specific YAML configs so that the DependencyTree can know about those sensor-specific composites.

The solution, I think, is to try to delay this composite loading until `.load`, use the `sensor` metadata from the existing data and/or readers, and make sure the dependency tree gets updated with this new information. This could also be done on `__setitem__` but not sure it needs to. Additional tasks and worries:

1. The dependency tree could be created during `.load` too, but this may complicate some things and may reveal some poorly written tests that are checking internal things like the state of the dependency tree.
2. I'd like eventually for the dependency tree and composite loading to be shared between multiple Scenes. This would be *huge* for MultiScene performance. Even resolving this specific issue will help creation of the Scene.
3. I've forgotten the other things I was going to write here...great.
