### ISSUE TITLE
Saving animation from Multiscene object with custom colormap and range

### ISSUE THREAD

**Issue by albe1982** [pytroll/satpy#1778]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to be able to save the frames of Multiscene object with a custom colormap (cmap) and data range (vmin, vmax)

**Describe the solution you'd like**
To have a function like existing "mscn.save_animation('{name}_{start_time:%Y%m%d_%H%M%S}.mp4', fps=2)" extended with option to apply colormap and data range.

**Describe any changes to existing user workflow**
/

**Additional context**
There are different possibilities through matplotlib/holomap/celluloid animations but they are complex to implement from non-developer point of view.

**Comment by djhoese** [comment]
This is part of a larger issue in Satpy in that you can not currently set enhancements (colormaps and linear ranges) from the runtime. They must be set in enhancement YAML configuration files. This should be made easier, but figuring out how to do within the existing interfaces is a challenge. Not everything comes down to a simple linear range with satellite data which is why the more complex enhancements were implemented. My other excuse is that Satpy is not a plotting library so these types of arguments didn't come to mind when first implementing things.

**Comment by albe1982** [comment]
Thank you very much for your fast answer. You made it so easy to export the animation from the Multiscene, and I hoped this could be the same case.

**Comment by djhoese** [comment]
I'm going to leave this open. My comment was not to say that we won't do this, just that it isn't super simple right now. This issue can serve as a marker for us to do it in the future.
