### ISSUE TITLE
Memory usage has increased drastically

### ISSUE THREAD

**Issue by pnuu** [pytroll/satpy#1791]
**Describe the bug**
I upgraded one of my production chains to use the latest Satpy, Pyresample and support libraries, and the chain ran out of memory.

**To Reproduce**

Run the below script with the following two setups and compare the memory usages:

* old packages (my previous operational environment)
  - satpy=0.24.0
  - pyresample=1.17.0
  - dask=2.30.0
  - numpy=1.19.4
  - xarray=0.16.1
* new packages (latest from `conda-forge`):
  - satpy=0.29.0
  - pyresample=1.20.0
  - dask=2021.7.2
  - numpy=1.21.1
  - xarray=1.9.0

Python 3.8 is used for both, as the older packages were not available for Python 3.9.

```python
#!/usr/bin/env python

import glob
import os
os.environ['PYTROLL_CHUNK_SIZE'] = "1024"
os.environ['DASK_NUM_WORKERS'] = "2"
os.environ['OMP_NUM_THREADS'] = "1"
import time
import datetime as dt

from satpy import Scene
import dask
from dask.diagnostics import ResourceProfiler, Profiler, CacheProfiler, visualize

def main():
    fnames = glob.glob(
        "/home/lahtinep/data/satellite/geo/goes-17/*s20201000300318*")
    comps = ["true_color", "overview", "colorized_ir_clouds"]
    glbl = Scene(reader='abi_l1b', filenames=fnames)
    glbl.load(comps, generate=False)
    lcl = glbl.resample(resampler='native')
    lcl.save_datasets(base_dir='/tmp/')


if __name__ == "__main__":
    # with dask.config.set(scheduler=CustomScheduler()):
    with Profiler() as prof, ResourceProfiler() as rprof, CacheProfiler() as cprof:
        tic = time.time()
        main()
        print("Elapsed time:", time.time() - tic)
    visualize([rprof, prof, cprof],
              file_path=dt.datetime.utcnow().strftime('/tmp/profile_%Y%m%d_%H%M%S.html'),
              show=False)
```

**Expected behavior**
The memory footprints should be comparable between the two versions.

**Actual results**
For the old package versions the peak memory usage is approximately 1.6 GB or RAM: With the newest versions memory usage jumps to approx. 4.6 GB.

**Screenshots**
Dask memory profile with old packages:
![Screenshot 2021-08-13 at 14-55-18 Bokeh Plot](https://user-images.githubusercontent.com/3170788/129353604-b8e0e42f-b6a8-4ae9-a926-219ef5f81066.png)

And with new packages:
![Screenshot 2021-08-13 at 14-55-09 Bokeh Plot](https://user-images.githubusercontent.com/3170788/129353644-657f1340-db0a-4668-a075-fb4c82bbc9cc.png)

**Environment Info:**
See above.

**Comment by pnuu** [comment]
After some iteration I pinned the increase down to Dask, and the first affected version to `2021.4.0`. The culprit seems to be https://github.com/dask/dask/pull/6322 which is also referenced in https://github.com/dask/dask/issues/7583 .

I think we should pin Dask version to `<=2021.3.1` which is the last usable version.

**Comment by simonrp84** [comment]
I tested this with very similar code to @pnuu, but using `ahi_hsd` instead of `abi_l1b` and resampling onto the `scn.coarsest_area()` area def to make sure it fits into my PC's memory.

My results, 'new' is dask `2021.7.2` and 'old' is dask `2021.3.1`:
New:
![dask_20217](https://user-images.githubusercontent.com/13449576/129368830-32a97907-6edc-4e1b-9471-be4afb271c18.png)
Old:
![dask_20213](https://user-images.githubusercontent.com/13449576/129368848-e8cbf06f-ba65-4983-b250-bfd17b63665a.png)

So the older dask is using ~65% of the memory of the new dask and processing takes around 60% of the time. Old dask a significant improvement!

**Comment by djhoese** [comment]
See https://github.com/dask/dask/pull/8040 for a partial solution. There are two things that dask was doing that made performance worse:

1. It was submitting all tasks to be run right at the beginning regardless of the number of available workers. This resulted in poor performance where memory was used up just to hold these tasks that couldn't be worked on.
2. The current strategy for dask task ordering does not serve Satpy the best as it could. See https://github.com/dask/dask/blob/4a59a6827578fdf8e105d1fb7e9d50d428c9d5fa/dask/order.py#L1-L77 for details. In the original version of my above PR, executing tasks in the reverse order of `dask.order` performed much better (5GB usage instead of ~8GB usage for generating true_color and overview of a RadC Scene). Related but not a solution for us: https://distributed.dask.org/en/latest/priority.html

**Comment by pnuu** [comment]
Closed with https://github.com/dask/community/issues/177 and Dask version `2021.8.1`.
