### ISSUE TITLE
Error occurred plotting Himawari-8

### ISSUE THREAD

**Issue by MengXin001** [pytroll/satpy#1828]
**Describe the bug**
When using `scn.crop` to plot H8 data in a specified area, an error will occur when the longitude beyond a certain range.  
As maximum longitude gets closer to the 180 longitude, the wrong lines will increase  

```python
channel="B13"
filenames = glob.glob('C:/Users/Administrator/Desktop/Sat/H8/HS*')
scn = Scene(filenames, reader='ahi_hsd')
scn.load([channel])
lonmin, latmin, lonmax, latmax = 105, 0, 180, 45
crop_scn = scn.crop(ll_bbox=(lonmin, latmin, lonmax, latmax))
data = crop_scn[channel].values
data = np.ma.array(data, mask=np.isnan(data))
area_def = crop_scn[channel].attrs['area']
lon, lat = area_def.get_lonlats()
lon, lat = np.ma.array(lon, mask=np.isinf(lon)), np.ma.array(lat, mask=np.isinf(lat))
lon, lat = lon.filled(), lat.filled()

plt.pcolormesh(lon, lat, data, transform=ccrs.PlateCarree())
```

**Screenshots**
max lon=155  
![H8_cartopy](https://user-images.githubusercontent.com/54111871/134038208-354df8c9-5fa8-44f7-9960-81b61bdab202.png)

max lon=170 
![H8_cartopy](https://user-images.githubusercontent.com/54111871/134038472-fbf8cea2-4b09-4c99-a0b1-1a1cbc9e62c0.png)

max lon=180 
![H8_cartopy](https://user-images.githubusercontent.com/54111871/134038720-751ea71f-e9b6-4575-98de-b08d6c31d0bc.png)

**Environment Info:**
 - OS: Windows & Linux]
 - Satpy Version: [0.29.0]

**Additional context**
What reason causes this problem? Is it a problem in my mask step?

**Comment by djhoese** [comment]
So I'm not convinced this is a Satpy problem. I think this is a matplotlib/cartopy issue or an issue with what you are trying to do. Let me explain. You are plotting geostationary data onto a platecarree (lon/lat degrees) map. You are also using pcolormesh which requires (from my understanding) 4 corner points per-pixel to be able to draw stuff properly. And then of course you are going over the anti-meridian so these coordinates are becoming non-contiguous/non-monotonic. Solutions and other things to try:

1. Try `plt.imshow(data, transform=ccrs.PlateCarree())`. If the data plots fine then we *know* it is a coordinate issue.
2. Try `lon[lon < 0] += 360`. That should make the points contiguous, but may still produce issues near the poles.
3. Plot in the geostationary projection (`area_def.to_cartopy_crs()`) instead of platecarree.
4. If none of this helps you may want to do some google searching or search on the cartopy issue tracker for open or closed issues regarding plotting over the anti-meridian.

**Comment by MengXin001** [comment]
Your detailed answers is greatly appreciated!  
I fixed it through the second method.  
![](https://user-images.githubusercontent.com/54111871/134109922-afb49c92-c9ce-4c64-8cad-99a59eac76a8.png)
