### ISSUE TITLE
keep `delta_time` instead of renaming to `offset_time`

### ISSUE THREAD

**Issue by zxdawn** [pytroll/satpy#1949]
**Describe the bug**

In the official TROPOMI products, it's `delta_time` but renamed to `offset_time`.
https://github.com/pytroll/satpy/blob/f9013963a632873731dee3d8f5c2112392495854/satpy/etc/readers/tropomi_l2.yaml#L45-L49

```
int delta_time(time=1, scanline=2906);
  :long_name = "offset of start time of measurement relative to time_reference";
  :units = "milliseconds since 2019-07-02 00:00:00";
  :_FillValue = -2147483647; // int
  :_ChunkSizes = 1U, 2906U; // uint
```

Is it better to keep it as the original name? I'm producing the data for some KNMI researchers. They usually use `delta_time`.

**Comment by djhoese** [comment]
It looks like you (@zxdawn) and @tommyjasmin are the main people who use/used this reader. @tommyjasmin originally wrote it and my guess is that this name change was either arbitrary or was to match existing software related to McIDAS/ADDE as part of is work at the SSEC. @tommyjasmin any memory of this?

**Comment by tommyjasmin** [comment]
Hi @zxdawn and @djhoese - I do not recall making any changes for this dataset, but I barely recall what I did a month ago :-)

I will look into it soon as I can (but today the meetings are thick).  I would not have changed it for McIDAS, since McIDAS-V has it's own Java reader (I wrote that too), and while I see an ADDE server in our future, the Python ADDE servers are still in their relative infancy.

**Comment by djhoese** [comment]
@tommyjasmin Thanks. The main question is why something called `delta_time` in the file was changed to be called `offset_time` in Satpy.

**Comment by zxdawn** [comment]
@tommyjasmin Thanks. And I'm not sure that the renaming of `time` is necessary:
https://github.com/pytroll/satpy/blob/bd784cac1923a7235514d2d5ab1202b451db4adb/satpy/etc/readers/tropomi_l2.yaml#L50-L54

**Comment by tommyjasmin** [comment]
Attn: @djhoese and @zxdawn 

Hello Xin - I am not sure why I renamed the delta_time variable in Satpy - the only reason I can think of is, possibly, because that's what the long_name attribute mentions (see below).  I think you can go ahead and change the .yaml for both of these variables as suggested if you have permission.  Otherwise I can do it.

  group: PRODUCT {
    variables:
      float delta_time(line=358, ele=450);
        :coordinates = "latitude longitude";
        :_FillValue = -2147483647; // int
        :long_name = "offset from reference start time of measurement";
        :units = "milliseconds";
        :_ChunkSizes = 1, 358, 450; // int

**Comment by zxdawn** [comment]
@tommyjasmin Got it! I will create a PR soon. Thanks.
