### ISSUE TITLE
Using cached geolocation and angles results in an error if chunk size not appropriately set.

### ISSUE THREAD

**Issue by simonrp84** [pytroll/satpy#1973]
**Describe the bug**
The new cached geolocation and satellite angles fails to function correctly if the `PYTROLL_CHUNK_SIZE` is not set to an integer factor of the level 1 image size.

**To Reproduce**

```python
from satpy import Scene
from glob import glob
import satpy

satpy.config.set({'cache_sensor_angles': True})
satpy.config.set({'cache_lonlats': True})
satpy.config.set({'cache_dir': '/tmp/satpy/'})

files = glob(f'*.DAT')

comp = 'true_color'

scn = Scene(files, reader='ahi_hsd')
scn.load([comp])
scn2 = scn.resample(scn.coarsest_area(), resampler='native')
scn2.save_datasets()
```

**Expected behavior**
the output files to be created, along with cache zarr files for the angles/lats/lons if not already available.

**Actual results**
If `PYTROLL_CHUNK_SIZE` is not set to an integer factor of the AHI image size then I get the following error:
```
  File "/home/proud/PycharmProjects/satpy/satpy/scene.py", line 1260, in load
    self.generate_possible_composites(generate, unload)
  File "/home/proud/PycharmProjects/satpy/satpy/scene.py", line 1319, in generate_possible_composites
    keepables = self._generate_composites_from_loaded_datasets()
  File "/home/proud/PycharmProjects/satpy/satpy/scene.py", line 1340, in _generate_composites_from_loaded_datasets
    return self._generate_composites_nodes_from_loaded_datasets(needed_comp_nodes)
  File "/home/proud/PycharmProjects/satpy/satpy/scene.py", line 1346, in _generate_composites_nodes_from_loaded_datasets
    self._generate_composite(node, keepables)
  File "/home/proud/PycharmProjects/satpy/satpy/scene.py", line 1370, in _generate_composite
    prereq_datasets = self._get_prereq_datasets(
  File "/home/proud/PycharmProjects/satpy/satpy/scene.py", line 1452, in _get_prereq_datasets
    self._generate_composite(prereq_node, keepables)
  File "/home/proud/PycharmProjects/satpy/satpy/scene.py", line 1404, in _generate_composite
    composite = compositor(prereq_datasets,
  File "/home/proud/PycharmProjects/satpy/satpy/modifiers/geometry.py", line 72, in __call__
    coszen = get_cos_sza(vis)
  File "/home/proud/PycharmProjects/satpy/satpy/modifiers/angles.py", line 287, in get_cos_sza
    lons, lats = _get_valid_lonlats(data_arr.attrs["area"], data_arr.chunks)
  File "/home/proud/PycharmProjects/satpy/satpy/modifiers/angles.py", line 150, in __call__
    self._cache_results(res, zarr_format)
  File "/home/proud/PycharmProjects/satpy/satpy/modifiers/angles.py", line 178, in _cache_results
    new_sub_res = sub_res.to_zarr(zarr_path,
  File "/home/proud/miniconda3/lib/python3.9/site-packages/dask/array/core.py", line 2708, in to_zarr
    return to_zarr(self, *args, **kwargs)
  File "/home/proud/miniconda3/lib/python3.9/site-packages/dask/array/core.py", line 3427, in to_zarr
    raise ValueError(
ValueError: Attempt to save array to zarr with irregular chunking, please call `arr.rechunk(...)` first.
```

**Comment by djhoese** [comment]
For a little more context as described on slack, this is only really a problem with segmented readers like AHI HSD (ABI L1b should not see this). In the ABI L1b case dask is given an entire image array and then told to chunk it. In the AHI HSD case it is given a segment of data, told to chunk it, and then told to concatenate them together. When telling satpy to use a chunk size of 1024 you then end up with a series of chunks of size (1024 1024, 152, 1024, 1024, 152, ...) which zarr doesn't like. Additionally the 152 rows for those end chunks is not going to give good performance since they are so small.

A good solution would be for us to update the AHI HSD reader (and others) to use `PYTROLL_CHUNK_SIZE` as a "hint" rather than an absolute value and base the final chunks used off of the size of a segment. For example if you set it to 2000 but the segment size was 2200 then you'd get a chunk size of 2200.

As noted on slack, @mraspaud would like to be able to specify a chunk size in megabytes (or other unit). This functionality is already provided by dask's "auto" chunking and the dask config value `array.chunk-size`. See https://docs.dask.org/en/stable/array-chunks.html#automatic-chunking for more information. We could even use a hard-coded chunk size for the row dimension  but use "auto" for the column dimension so that chunks always include all the segment's rows.

In the long run `PYTROLL_CHUNK_SIZE` should be deprecated (slowly) in favor of dask auto chunking or as an alternative to pytroll chunk size a `satpy.config` parameter.

**Comment by Plantain** [comment]
This doesn't happen only with PYTROLL_CHUNK_SIZE set incorrectly, it also happens with any crop operation.

Any crop before resampling will subsequently fail to resample due to this.

For example, with AHI data:
scn = scn.crop(xy_bbox=(-4700000,-5000000,4500000,4500000))
scn = scn.resample(scn.finest_area(),resampler='native')

throws: "ValueError: Attempt to save array to zarr with irregular chunking, please call `arr.rechunk(...)` first."

**Comment by djhoese** [comment]
I just made https://github.com/pytroll/satpy/pull/2041. If either of you have time to test it it would be greatly appreciated.
