### ISSUE TITLE
Why the lon/lat is interpolated to 1km while data are still 5km for MOD06 product

### ISSUE THREAD

**Issue by zxdawn** [pytroll/satpy#2037]
**Describe the bug**

The lon/lat in MOD06 product are interpolated automatically to 1km, but the products are not.

**To Reproduce**

```python
from satpy import Scene

scn_modis = Scene(['../data/modis/MOD06_L2.A2019223.0245.061.2019223133650.hdf'], reader='modis_l2')
scn_modis.load(['cloud_top_pressure_infrared', 'longitude', 'latitude'])

print(scn_modis['longitude'].shape, scn_modis['cloud_top_pressure_infrared'].shape)
```

Output:
```
(2030, 1354) (406, 270)
```

**Expected behavior**

How to just keep the original data resolution? Is it necessary to interpolate to 1km?

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.33.1

**Comment by djhoese** [comment]
Is there a reason you are loading the lon/lats separately instead of getting it from the SwathDefinition from the `.attrs['area'].get_lonlats()` method?

The `cloud_top_pressure_infrared` product doesn't have a 1km variant:

https://github.com/pytroll/satpy/blob/0a5acaa58c3288d5303a85816cebf5528bac755b/satpy/etc/readers/modis_l2.yaml#L491-L499

Since you are loading the lon/lats separately you are telling Satpy "give me the longitude and latitude variables at the highest resolution possible". Lon/lats can be interpolated to higher resolutions, the products can not. So bottom line is this is all expected.

**Comment by zxdawn** [comment]
Ha, I forgot I can get lon/lat from `.attrs['area'].get_lonlats()`. It works well now.

But, why does loading lon/lat return the highest resolution?
Because the lon/lat in the file is 5 km, is it meaningful to interpolate it to 1 km automatically?

**Comment by djhoese** [comment]
Typically lon/lat arrays in MODIS are "supposed" to be interpolated for the L1b data and any L2 products that are 1km. Most l1b bands are at 1km but the lon/lats that come in the band files are at 5km. Regardless, Satpy's general policy and assumption is that if a user requests a product with the generic product name that the user wants the highest resolution possible. Besides performance reasons, there is rarely (in my experience) a reason for someone to want a lower resolution product.

**Comment by zxdawn** [comment]
Thanks for the explanation. It makes sense. Close now ;)
