### ISSUE TITLE
Strange behaviour when trying to load data to a scene object after having worked with it

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#208]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import xarray as xr
from glob import glob
import os
from satpy import Scene
from satpy.utils import debug_on
debug_on()

TEST = True

BASEDIR = "/home/a000680/data/polar_in/direct_readout/eos/lvl1/"

scn = Scene(filenames=glob(os.path.join(BASEDIR, "*A16090_1143*hdf")), reader='hdfeos_l1b')
comp_names = ['true_color', 'true_color_land']
scn.load(comp_names)

areaid = "mediterranean_east"
lcn = scn.resample(areaid, mask_area=False, radius_of_influence=5000)
lcn.show('true_color')

if TEST:
    x = lcn['true_color'].copy()
    composite_name = "true_color_land_and_sea"
    x.attrs['name'] = composite_name

    x1 = x.values
    land_rgb = lcn['true_color_land'].values
    mask = False
    x1[:, mask] = land_rgb[:, mask]

    lcn[composite_name] = xr.DataArray(x1, dims=lcn['true_color'].dims,
                                       coords=lcn['true_color'].coords,
                                       attrs=lcn['true_color'].attrs)


scn.load(['solar_azimuth_angle', 'solar_zenith_angle',
          'satellite_zenith_angle', 'satellite_azimuth_angle'], resolution=1000)

```

#### Problem description

If you run the above code as if (`TEST=True`) you get the output:

```
TypeError                                 Traceback (most recent call last)
/home/a000680/laptop/Pytroll/demo/modis/satpy_issue_5march2018.py in <module>()
     59 
     60 scn.load(['solar_azimuth_angle', 'solar_zenith_angle',
---> 61           'satellite_zenith_angle', 'satellite_azimuth_angle'], resolution=1000)

/home/a000680/usr/src/satpy/satpy/scene.pyc in load(self, wishlist, calibration, resolution, polarization, compute, unload, **kwargs)
    639             raise KeyError("Unknown datasets: {}".format(unknown_str))
    640 
--> 641         self.read(**kwargs)
    642         keepables = None
    643         if compute:

/home/a000680/usr/src/satpy/satpy/scene.pyc in read(self, nodes, **kwargs)
    580             required_nodes = self.wishlist - set(self.datasets.keys())
    581             nodes = self.dep_tree.leaves(nodes=required_nodes)
--> 582         return self.read_datasets(nodes, **kwargs)
    583 
    584     def compute(self, nodes=None):

/home/a000680/usr/src/satpy/satpy/scene.pyc in read_datasets(self, dataset_nodes, **kwargs)
    443             if ds_id in self.datasets and self.datasets[ds_id].is_loaded():
    444                 continue
--> 445             reader_name = node.data['reader_name']
    446             reader_datasets.setdefault(reader_name, set()).add(ds_id)
    447 

TypeError: 'NoneType' object has no attribute '__getitem__'
```

But when you have `TEST=False` it runs fine!

PS: The thing I do in the TEST part is nonsense, I know. But I have removed as much code as possible to be still able to reproduce the error!

#### Versions of Python, package at hand and relevant dependencies

Python 2.7.5
Satpy: most recent feature-smac-test (March 5, 2018)

**Comment by davidh-ssec** [comment]
Here are my current guesses:

1. Resampling the dataset incorrectly erases the dependency tree attribute of the original scene when creating the new Scene.
2. Setting a new dataset may be adding a Node to the dependency tree and not properly copying that dependency during resampling. I can't recall what adding datasets does to the dependency tree.

**Comment by davidh-ssec** [comment]
@adybbroe I've figured out the problem and have fixed part of it. I wasn't able to finish all the fixes before being done for the night. I'll get to it tomorrow. There are actually two issues here:

1. The dependency tree thinks it is being copied when you make a new Scene, but the copy doesn't seem to be correct. I don't want to rush fixing this since doing it wrong will show up later. I also have to be careful that nodes in the dependency tree are unique. For example, if a composite depends on a dataset that you also asked for (`scn.load(['comp', 'ds1'])` the tree entries for `ds1` should both be the same Node object.

2. The loading of datasets wasn't made to handle datasets added by users. So it sees a dependency tree "leaf" node (the dataset you added yourself) and expects it to have come from a reader.

So what happens is you add your new dataset to the second scene which adds a node to its dependency tree, BUT that dependency tree is actually the same dependency tree from the original Scene due to issue 1 above. Then you ask to read more datasets, it sees the node for the dataset you added to the second scene and then dies due to issue 2 above.
