### ISSUE TITLE
satpy_cf_nc reader to support variables with same name but different attributes

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#2286]
## Feature Request

I have stored from VIIRS SDR these data in 3 different netcdf file with the satpy_cf_ns writer. On file for each Iband, Mband and DNB.
When creating composites with data from one of these files it works fine. However if I need composites with data from two or more files I get problems.

It turns out the satpy_cf_nc reader only uses the variable name to confirm the usage. This causes eg.  solar_zenith_angle to be fetch from either M or I band ( or both, I'm not sure) giving exceptions like this:
```
ValueError: cannot reindex or align along dimension 'x' because of conflicting dimension sizes: {6400, 3200}
``` 

After discussion https://pytroll.slack.com/archives/C0LNH7LMB/p1668716226338369, David suggested this part of the code beeing the problem:
https://github.com/pytroll/satpy/blob/main/satpy/readers/satpy_cf_nc.py#L290-L294

If I add a few lines after https://github.com/pytroll/satpy/blob/main/satpy/readers/satpy_cf_nc.py#L292

```
        try:
            if data.attrs['resolution'] != ds_id['resolution']:
                return
        except KeyError:
            pass
```
I get the expected output.

But I need some advice if this is a good solution or if this should be handled somewhere else.

**Comment by djhoese** [comment]
I'm curious what @mraspaud thinks of this. I thought maybe @TAlonglong could make a DataID from the `data_arr.attrs`, but then he'd need the `id_keys`, but those are in a hidden parameter on the DataID provided to `get_dataset` and are otherwise not available to the file handler.

So then I thought we could just do `data_id == data_arr.attrs`, but it doesn't look like that handles non-DataIDs. So I guess the only solution is to iterate through the `data_id.to_dict()` for keys that are also in `data_arr.attrs` and see if the values are the same (maybe excluding `modifiers`). Thoughts @mraspaud ?
