### ISSUE TITLE
Question: How to understand "satpy.enhancements.ahi.jma_true_color_reproduction"?

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#2374]
I'm not trying to discuss the science theory behind this, but the algorithm itself. How it works? For personal interests, I want to do the same enhancement by my own code. So I want to figure this out. For example, if I got R, G, B bands separately, not combined in a RGB composite, how can I apply it for each band?

**Comment by djhoese** [comment]
I could be wrong, but I think if you copy this usage of the enhancement:

https://github.com/pytroll/satpy/blob/bffa2fb51fec65a7ca809caa172402328e4d6c14/satpy/etc/enhancements/ahi.yaml#L13-L23

But change the `standard_name` to match your data then it should work. You could also change `standard_name: ` to `name: ` and give the exact name of the products you want it to be applied to. If you include the "stretch" part of this configuration and you're not doing an RGB composite you'll need to change the min/max arguments from 3 elements to a single scalar value since you'll only be dealing with 1 band instead of 3 RGB bands.

Let me know how it goes.

**Comment by yukaribbba** [comment]
@djhoese Thanks but actually I was talking about [https://satpy.readthedocs.io/en/latest/_modules/satpy/enhancements/ahi.html#jma_true_color_reproduction](https://satpy.readthedocs.io/en/latest/_modules/satpy/enhancements/ahi.html#jma_true_color_reproduction)...

**Comment by djhoese** [comment]
Unless I'm missing something, that is exactly the function used in this enhancement configuration. See the first `method:` parameter under the `operations` list.

If you're wondering how to call this function from Python directly, without Satpy or YAML configurations, then you'll want to import the function and pass it a `trollimage.xrimage.XRImage` object. That `XRImage` object can be given an xarray `DataArray` with your data in it.

**Comment by yukaribbba** [comment]
> If you're wondering how to call this function from Python directly, without Satpy or YAML configurations, then you'll want to import the function and pass it a `trollimage.xrimage.XRImage` object. That `XRImage` object can be given an xarray `DataArray` with your data in it.

Further, I'm trying to rebuild that function with GDAL array data. Now I know how -- just simply stack three bands data together. Well looks like I overthought it.

```
r_data = ...(GDAL ReadAsArray data)
g_data = ...(same as r)
b_data = ...(same as r)

img_data = np.array([r_data, g_data, b_data])
ccm = np.array([
        [1.1759, 0.0561, -0.1322],
        [-0.0386, 0.9587, 0.0559],
        [-0.0189, -0.1161, 1.0777]
    ])
output = np.dot(img_data.T, ccm.T)
output = ouput.T
```
It works perfect. So I'm closing now.
