### ISSUE TITLE
Fail to install satpy despite the version

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#2458]
Looks like this happened after 0.42 upgrade. It's always solving environment:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
```
I'don think there's something wrong with my conda config since other packages like gdal went well.

**Comment by djhoese** [comment]
Could you please give more context? What command are you running? If this was an existing environment what version of python and other tools were inside already? What operating system?

**Comment by yukaribbba** [comment]
@djhoese Sorry for lacking details. I'm using the latest miniconda x64 version (https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-x86_64.exe) on a Windwos 11 22H2 pc. The python is 3.10.10 and the conda is 23.3.1. This is a newly-setup environment. To install satpy I used `conda install -c conda-forge satpy`.

**Comment by yukaribbba** [comment]
After nearly half an hour solving environment finally ended and packages came up. This is too much longer than I expected.

**Comment by pnuu** [comment]
The default conda package solver is quite slow. Try installing `mamba` with `conda install mamba` and using that next time instead of `conda` when updating/installing packages. Or go directly to [mambaforge](https://github.com/conda-forge/miniforge#mambaforge) (my preferred Conda variant). Or as a third option, install Satpy when creating the environment `conda env create -n newenv python=3.10 satpy`, that way the package solving is much simpler.

As this is not a Satpy issue but a conda package interdependency conflict resolving issue, I'm closing this.

**Comment by djhoese** [comment]
I just want to add something to this. Satpy is a pure python package so it's binary conda packages are relatively flexible as far as what packages it can be mixed with in an environment. However, it depends on a lot of complex compiled platform-specific packages like rasterio (which depends on gdal), numpy, and it pulls in netcdf and hdf5 in the conda package. These dependencies are the reason this solving is slow, not satpy. You could also speed up the solving by including satpy as one of the packages specified when the environment is created as the solver then has all packages in mind from the initial creation.

**Comment by yukaribbba** [comment]
@pnuu Miniforge is good. Thanks for suggestion! :)
