### ISSUE TITLE
Wrong version numbers at readthedocs

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#2566]
**Describe the bug**

The version number at https://satpy.readthedocs.io/en/stable/overview.html is wrong.  At present, the website title says

> Overview — Satpy 0.1.dev1407+g18288df.d20230807 documentation

**To Reproduce**

```bash
curl -s https://satpy.readthedocs.io/en/stable/overview.html | grep -o "<title>[^<]*" | tail -c+8
```

**Expected behavior**

`Overview &mdash; Satpy 0.43.0 documentation`

**Actual results**

`Overview &mdash; Satpy 0.1.dev1407+g18288df.d20230807 documentation`

**Environment Info:**
 - OS: not relevant
 - Satpy Version: 0.43.0

**Additional context**

It looks like the git tags are not imported prior to version number calculation.

**Comment by djhoese** [comment]
The commit SHA shown for "stable" matches the `v0.43.0` tag so it looks like it at least built the correct commit, it just didn't have the tag information for some reason. I've started a fresh build of "stable" to see if it was a RTD or GitHub bug and if it might have "fixed itself" since our last release.

![image](https://github.com/pytroll/satpy/assets/1828519/069df91a-d278-45c6-a88b-9b3a294b4838)

**Comment by djhoese** [comment]
FYI I filed a bug report with readthedocs and I also have #2567 where I'm applying some of the things suggested from the RTD issue.
