### ISSUE TITLE
Can reader 'modis_l1b' correct MODIS Bow Tie Effect?

### ISSUE THREAD

**Issue by yhyxzx** [pytroll/satpy#2581]
Can reader 'modis_l1b' correct MODIS Bow Tie Effect?

**Comment by djhoese** [comment]
The MODIS bow tie is "corrected" by resampling data using the `Scene.resample` interface. The bow tie is "detected" by recognizing the fill values associated with those pixels and then ignored when they are resampled.

If you are looking to keep the data in the native swath structure but want to some how exclude the bow-tie pixels let me know. That is a much different conversation though.

**Comment by yhyxzx** [comment]
@djhoese Does `Scene.resample` work like `Geometric Correction > Reproject GLT with Bowtie Correction` in envi? Is the result similar to the third figure in the link, "_**Georeferenced image with bow tie correction**_"[https://www.nv5geospatialsoftware.com/docs/ApplyingCorrectionForMODISBowTieEffect.html](url)

**Comment by djhoese** [comment]
I have no experience with ENVI, but yes I think so. It is strange to me that they have a resampling *without* bow tie correction since treating the data as it is meant to be treated (knowing which pixels are fill values and ignoring them during resampling) gets you this bow tie correction for free.

Satpy uses pyresample under the hood for resampling. Here is pyresample's description of resampling:

https://pyresample.readthedocs.io/en/latest/concepts/resampling.html

**Comment by yhyxzx** [comment]
In this process, is a more advanced product MOD03 necessary? @djhoese

**Comment by djhoese** [comment]
MOD03 is the geolocation product, right? While you might get "OK" results using the geolocation that comes in the data files, I will always recommend using the higher resolution geolocation information in the MOD03 files. It should also speed up processing as you shouldn't need to interpolate the geolocation as much.
