### ISSUE TITLE
How to find the appropriate values of parameters in Scene.resample() function using Himawari Data

### ISSUE THREAD

**Issue by xuesongle** [pytroll/satpy#268]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
# Your code here
from satpy.scene import Scene
from satpy.resample import get_area_def
from datetime import datetime
from glob import glob

FILES = glob("/home/griffith/GIS/testData/*DAT")

scn = Scene(sensor='ahi',start_time=datetime(2017, 6, 23, 2, 50),end_time=datetime(2017, 6, 23, 3, 00),filenames=FILES,reader='ahi_hsd')
rgbname = 'true_color_reducedsize'
#scn.load([rgbname])
#scn.show(rgbname)

print(scn.available_dataset_names())
scn.load(["B01"])
local_scene = scn.resample("("eurol")
```
#### Problem description

I am trying to find a local scene from Himawari HSD data but really struggle to find out the parameter value of "destination" in resample function here. If I want to get a local scene in Australia, what is the value there. Does anyone known where to find the documentation about the which value should be used for different types of Satellite data.

#### Actual Result, Traceback if applicable

                                      ^
SyntaxError: invalid syntax
#### Versions of Python, package at hand and relevant dependencies
python3.6

Thank you for reporting an issue !

**Comment by davidh-ssec** [comment]
@xuesongle You have a syntax error (as your error message says) which means your python code is formatted incorrectly. If you look at the last line you have `"("eurol")`, that is three quotation marks. You want to do `local_scene = scn.resample("eurol")`. After that works for you let me know if you still need help.

**Comment by xuesongle** [comment]
I just updated it and the question is about where to find the value for a local scene such as Australia, . Does anyone known where to find the documentation about the which value should be used for different types of Satellite data.

**Comment by davidh-ssec** [comment]
Instead of an area name string you can provide an `AreaDefinition` object. See the documentation for those objects here:

http://pyresample.readthedocs.io/en/latest/geo_def.html#areadefinition

I believe there are also utility functions for creating an AreaDefinition from a set of coordinates but I can't seem to find them in the documentation right now. Perhaps @mraspaud could point out any utilities that exist when he starts his day in a couple hours. Otherwise, I'll be online tomorrow if you need more help.

**Comment by xuesongle** [comment]
@davidh-ssec, thank you very much for the prompt help. As I am new to both python and SatPy, The dumb question is how to save the the local scene into a image. As I attempted the following code:
from satpy.scene import Scene
from satpy.resample import get_area_def
from datetime import datetime
from glob import glob

FILES = glob("/home/griffith/GIS/testData/*DAT")

scn = Scene(sensor='ahi',start_time=datetime(2017, 6, 23, 2, 50),end_time=datetime(2017, 6, 23, 3, 00),filenames=FILES,reader='ahi_hsd')
rgbname = 'true_color_reducedsize'
#scn.load([rgbname])
#scn.show(rgbname)

print(scn.available_dataset_names())
scn.load(["B01"])
#scn.show("B01")
scn.save_datasets(writer='simple_image')
print(scn.available_composite_names())

local_scene = scn.resample("eurol")
#local_scene.show("B01")
local_scene.save_datasets(writer='simple_image')

And I got an image with 10k. Which step did I got wrong?

**Comment by davidh-ssec** [comment]
> an image with 10k

What do you mean by "10k"? For now, until you get a good local AreaDefinition for `scn.resample`, I would comment out all of the `local_scene` lines.

If you are getting unexpected images it is likely because your `scn.save_datasets(...)` results are being overwritten by your `local_scene.save_datasets(...)` call which probably doesn't have much data in it, if any. Those two calls will save results to the same filename by default.
