### ISSUE TITLE
Scene from memory

### ISSUE THREAD

**Issue by sfinkens** [pytroll/satpy#396]
**Is your feature request related to a problem? Please describe.**
I have bz2 compressed images which must be decompressed to disk before I can read them in satpy. In order to reduce IO I would like to decompress them into memory and use that data to create a satpy scene. I couldn't figure out how to do that.

**Describe the solution you'd like**
Add an optional ``file_handles`` argument to the ``satpy.Scene`` constructor enabling the user to specify a file handle to every given filename. Instead of reading a file from disk, the ``read()`` method of the corresponding file handle would be called. Example:

    from satpy import Scene
    import bz2
    import io
    import glob
    import os

    filenames_bz2 = glob.glob('HS_H08_20180118_1230_B13_FLDK_R20_S??10.DAT.bz2')
    filenames = [os.path.splitext(fname)[0] for fname in filenames_bz2]
    file_handles = [io.BytesIO(bz2.BZ2File(fname).read()) for fname in filenames_bz2]
    scene = Scene(filenames=filenames, reader='ahi_hsd', file_handles=file_handles)

**Describe any changes to existing user workflow**
None, the new argument would be optional.

**Additional python or other dependencies**
None

**Describe any changes required to the build process**
None

**Comment by djhoese** [comment]
I have actually considered use cases like this before and it is something I would like satpy to be able to do (read data from other sources besides directly on disk). One thing that should work for you, but it is not heavily tested, is to provider a `Reader` instance as the `reader` argument to the `Scene` rather than add a new keyword argument to the Scene.

This also isn't a simple thing that we would want users to have to "manually" do in their own code so we would want to add this internally in to satpy's readers, perhaps even to a specific set of readers. Put another way, expecting users to make custom file reading utilities (using bz2, etc) that get passed to the existing reader interfaces doesn't make sense as an interface. The reader classes and the file handler classes they user are there for a reason. We also depend heavily on dask and xarray which may already have solutions for lazy-loading compressed data.

@sfinkens Do you expect to need other file formats (more than just HSD) to be readable from compressed files too? This seems like it is very specific to what the format is and if the libraries used underneath can handle compressed data well. I think the right way to implement this type of functionality is to customize/subclass or add on to the existing reader or file handlers. In your current example you are actually reading the data files in to memory. It may be best/preferred to include this type of logic in a dask Delayed function so that the data isn't loaded in to memory until it is actually needed (like all other dask functionality).

**Comment by crazyapril** [comment]
I think to add on to the existing reader/file handler is the right way because 1) this can easily make `find_files_and_readers` applicable for compressed files while a custom interface cannot 2) other than compressed files in some very specific formats I don't think there is much need for that functionality

**Comment by djhoese** [comment]
Good points @crazyapril. Also there is other functionality provided by readers that may not be easy to implement in the proposed adhoc keyword argument interface. Things like what products are available in the file, what is the area definition of the file, etc. This really depends a lot on what exactly gets passed to the Scene in this new keyword though and how it gets used.

**Comment by sfinkens** [comment]
Many thanks for your explanations and suggestions! Obviously I underestimated what is happening under the hood. I will try customizing an existing reader.

@djhoese Since we are working with 15+ years of historical geostationary data, most of the files are compressed in order to save disk space.

**Comment by sfinkens** [comment]
I managed to get that done for the AHI HSD reader. Replacing the ``open()`` calls was straightforward, but it turned out that ``numpy.fromfile`` and ``numpy.memmap`` do not support ``io.BytesIO`` buffers. Fortunately somebody found a workaround (https://github.com/adamreeve/npTDMS/pull/48). The memory map is essentially replaced by a simple array, but that doesn't matter because the whole file is already in memory anyway.

I tried to refactor the file handler class so that it is easier to subclass: https://github.com/pytroll/satpy/compare/master...sfinkens:ahi_hsd_bz2

Based on that class you can define your own customization:

    from satpy.readers.ahi_hsd import AHIHSDBaseFileHandler
    import numpy as np
    import io
    import bz2file
    
    
    class bz2open(object):
        """Decompress multi-stream bz2 compressed files into memory"""
        def __init__(self, filename, size=-1):
            """
            :param filename: bz2 compressed file to be opened
            :param size: Number of bytes to be decompressed. If negative: Read the
            whole file.
            """
            self.filename = filename
            self.size = size
    
        def __enter__(self):
            """
            :return: File-like io.BytesIO buffer
            """
            self.decomp_file_handle = io.BytesIO(
                bz2file.BZ2File(self.filename).read(self.size))
            return self.decomp_file_handle
    
        def __exit__(self, exc_type, exc_val, exc_tb):
            self.decomp_file_handle.close()
    
    
    class AHIHSDBz2FileHandler(AHIHSDBaseFileHandler):
        def _open(self, filename, mode='r', size=-1):
            """Open a bz2 compressed file and decompress the given number of
            bytes into memory."""
            return bz2open(filename, size=size)
    
        def _read_header(self, file_handle, dtype, count):
            """Wrapper around numpy.fromfile to support BytesIO buffers.
    
            Copied from https://github.com/adamreeve/npTDMS/pull/48
            """
            return np.fromstring(file_handle.read(count * dtype.itemsize),
                                 dtype=dtype, count=count)
    
        def _read_data(self, filename, file_handle, dtype, shape):
            """numpy.memmap does not support BytesIO buffers.
            Workaround: Create a simple numpy array from the buffer."""
            num_elem = np.array(shape, dtype='i8').prod()
            return self._read_header(file_handle, dtype=dtype, count=num_elem).reshape(shape)

And then use it as follows:

    from satpy import Scene
    from satpy.utils import logging_on
    import glob
    import logging
    import matplotlib.pyplot as plt
    
    logging_on(level=logging.DEBUG)
    
    # Create scene from uncompressed files
    filenames = glob.glob('HS_H08_20180118_1230_B13_FLDK_R20_S??10.DAT')
    scene = Scene(filenames=filenames, reader='ahi_hsd')
    scene.load(['B13'])
    
    # Create scene from bz2 compressed files
    filenames_c = glob.glob('HS_H08_20180118_1230_B13_FLDK_R20_S??10.DAT.bz2')
    scene_c = Scene(filenames=filenames_c, reader='ahi_hsd_bz2', ppp_config_dir='.')
    scene_c.load(['B13'])
    
    # Show results
    diff = scene['B13'] - scene_c['B13']
    print(diff.min(), diff.max(), diff.mean())
    
    
    plt.figure()
    plt.imshow(scene['B13'])
    plt.colorbar()
    plt.title('From uncompressed files')
    
    plt.figure()
    plt.imshow(scene_c['B13'])
    plt.colorbar()
    plt.title('From compressed files')
    
    plt.show()

At the moment I have a file ``ahi_hsd_bz2.yaml`` in the current working directory which is basically a copy of ``ahi_hsd.yaml`` but with a ``.bz2`` appended to the file patterns. Is there a way to import the channel definitions from another file? 

@djhoese You proposed to make use of dask delayed functions. Where would you recommend to do so? I have no experience with dask.

**Comment by djhoese** [comment]
Regarding channel definitions, no not right now. You either have to copy the reader name (`ahi_hsd.yaml`) in your local custom version and only modify the parts you need. However, in your case you may be able to include your bz2 work inside the existing reader. However, if you have to make a bz2 version for all readers I'm a little worried about clutter and keeping them up to date with any future changes. For a particular channel you can list multiple file types (as a list in YAML) and satpy will use the first file type that is available.

For the dask stuff, if the existing reader doesn't use it heavily then it may be more work than you want to do. I was thinking something like this:

```python
from dask import delayed
import dask.array as da
from satpy import CHUNK_SIZE

def func_using_open(...):
    return array_we_got_from_opening_the_file

delayed_open = delayed(func_using_open)
delayed_arr = da.from_delayed(delayed_open, shape=(rows, cols), dtype=np.float32, chunks=CHUNK_SIZE)

This assumes you can figure out the rows/cols and maybe the dtype from the header without having to load the entire file. I'm guessing that isn't exactly possible.
```

**Comment by sfinkens** [comment]
> However, if you have to make a bz2 version for all readers I'm a little worried about clutter and keeping them up to date with any future changes.

Absolutely. I will live with the I/O overhead then. Unless you consider refactoring the existing readers making it easier to inject a custom ``open`` method etc without touching the actual reading logic. I would be willing to help :)

**Comment by djhoese** [comment]
> Unless you consider refactoring the existing readers making it easier to inject a custom open method

From my point of view it doesn't make sense to add this as a general feature. I don't think it would work for all readers and would make changing the reader interfaces difficult in the future. It also causes more and more of the reader internals to bleed in to the Scene interface (cluttering documentation/docstrings). Our goal as we clean up the Reader and file handler interfaces is to make it dead simple for a new user/contributor to add their own reader. While it may seem like "then let them pass a function to the Scene" is the easiest way to go, it doesn't actually add the functionality to satpy long-term which doesn't help satpy or the community.

All of that said, depending on your actual workflow, what if you just wrapped your satpy usage code in an extraction process that wrote to `/dev/shm` on *nix machines where SatPy could then pull the data in? `/dev/shm` is a ram disk so that data is actually in memory and should provide the same relative speeds as loading it with python. Not sure how big `/dev/shm` usually is and how much data you plan on processing at one time. @mraspaud and @pnuu may have experience doing something like this too, feel free to comment.

**Comment by sfinkens** [comment]
Ok I see, that makes sense. The idea with ``/dev/shm`` is brilliant! I never heard of it! That should indeed solve the problem. I only need two images at a time, so size shouldn't be an issue. Thanks a lot!

**Comment by djhoese** [comment]
I'm going to close this for now. If we decide in the future to add this to satpy proper then we can reference all the work you've done. If other users need functionality like this then we can move this up the priority list.
