### ISSUE TITLE
Interactively set the Calibration Mode when creating the Scene Object

### ISSUE THREAD

**Issue by ColinDuff** [pytroll/satpy#521]
For the MSG Level1.5 data we would like to be able to set the calibration mode eg GSICS or Nominal when creating the Scenes Object

setting the calibMode and passing this into the Scene init as a reader_kwargs

```python
kwargs = {"calibMode": "GSICS",}
scn = Scene(
          sensor="seviri",
          reader="native_msg",
          filenames=[path+fname],
          reader_kwargs=kwargs
          )
```

need to pass the reader_kwargs from the Scene init to the File Class handler

Currently we use an environment variable

**Comment by djhoese** [comment]
As mentioned on slack, this is a known limitation. I'm fine having the kwargs passed to the file handler, but I think the *cleanest* solution is to subclass the base yaml reader and have it pass the keyword arguments to the file handler explicitly. Otherwise we get in to the base yaml reader handling this logic which means changing the base file handler interface and updating *all* existing file handlers. Again, I'm ok doing something like this, but it gets complex and also probably means doing more `**kwargs` which I know @mraspaud and @pnuu hate.
