### ISSUE TITLE
Resample adds junk to image

### ISSUE THREAD

**Issue by jakeri** [pytroll/satpy#64]
I'm using the satpy to resample to some different areas. Sometimes the image get green junk in it.
Input is a MSG3 nat file.

I get the feeling that it is related to 'overview' and night time images.

![untitled 9](https://user-images.githubusercontent.com/76497/30117035-5ccc813c-931f-11e7-83f5-e7921a184981.png)
Broken one. 00:30Z

![untitled 6](https://user-images.githubusercontent.com/76497/30117042-62bb542e-931f-11e7-9310-8a42d2140d42.png)
Other broken one. 03:30Z

![untitled 7](https://user-images.githubusercontent.com/76497/30117049-6655f36e-931f-11e7-8a4f-ab77abbd7afb.png)
This is basically what I want. 04:30Z

Do you have any ideas how I can mitigate this?

**Comment by adybbroe** [comment]
Some of the satpy developers can give you the details, in the mean time here is my comments.
Also check the documentation on making a custom composite and checkout the stretch method, it might take arguments to cutoff the lower and upper part of the histogram before stretching, that would help I believe.

During nighttime there is very little (if any) information content in the red and green channels (the shortwave bands). The data (reflectance) may not be exactly zero every where, either due to calibration uncertainties or sometimes due to straylight (especially this time of year).

The custom overview composite does a linear stretch. I am not sure exactly how that linear stretch is designed, and if it use a simple cutoff. Usually we make a histogram of the data and take a way a few percent on each of the tails, and then stretch the data. 

Really one should not construct an overview RGB during nighttime.

**Comment by davidh-ssec** [comment]
I know more about the code, but less about the overview RGB. The default enhancement for the `"overview"` composite is to invert the `B` channel, normalize each channel separately to a 0-1 range based on their individual min and max values, lastly a gamma correction of 1.6 is applied (to make it darker). @mraspaud can probably comment better than me on whether this scaling is best for an overview image.

I'm also wondering if there are some negative values in any reflectance bands involved and if that might be screwing up the stretch.

**Comment by pnuu** [comment]
Those faulty pixels are noise, values barely above 0 % reflectance. As @adybbroe said, there's no actual signal during night on the visible and NIR channels, only some noise. My solution has been not to make composites using reflective channels during night :-) If you want to have the same composite available 24/7, then I'd add masking based on sun zenith angle (mask areas where SZA > 92 degrees, or so) for the affected channels.

I prefer to have static stretching limits for most composites, and use these limits for `overview`: R = `[0, 1]`, G = `[0, 1]`, B = `[-280, -200]` (not sure how the values should be given to the inverted infrared channel in satpy).

**Comment by jakeri** [comment]
Thank! That explains it.
