### ISSUE TITLE
Separate file discovery from Scene init

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#82]
There are currently two methods for initializing a Scene:

1. Provide the filenames for the files to be read as input. Optionally provide the name (or instance) of the reader to be used to open the provided files.
2. Provide information for sorting through available on-disk files in a `base_dir` and discover which reader should be used and which files match the parameters.

It has been determined from off-github conversation that the 2nd method should be separated out in to its own function. The keywords required to perform both methods being in the same `__init__` method has caused confusion among users, especially when compared to the legacy mpop interface.

Questions to answers:

1. Should the discovery function be available as a separate utility function or Scene classmethod? If utility function, where should it be located and should it be added to `satpy/__init__.py`? 
2. What keywords related to file and reader loading are presented in `Scene.__init__`?

    reader
    filenames
    reader_kwargs
    others?

3. Is `reader` still optional in the Scene init? Making it optional would allow the user to provide multiple formats of files and have multiple readers created to read those files. A feature that isn't heavily tested, but is intended to work.
4. Does the discovery function return a list of files or a dictionary of `reader_name: [filenames]`?
5. Do we allow for filtering based on metadata in the `Scene.__init__`? Does it have to be metadata only available inside the file or can it be metadata available from the filename? I believe filtering on filename metadata is currently available via the discovery functionality.
6. Does separating these interfaces stop us or make it more difficult to add certain features in the future?
7. Do we also change `**metadata` to just `metadata` or even remove it all together? Its function is to add metadata to the `Scene.info` dictionary.

**Comment by pnuu** [comment]
1. Yes, probably. Although I don't intend to use it my self, maybe someone will find it useful. Class method calling an external utility function, maybe?

2. reader (list of readers to be tried could be useful, see 3.) and filenames are the ones I've used.

3. I would keep it optional. For one, it helps when discovering the reader name which I tend to forget, and also the occasional/potential need for several different filetypes (eg. reading SEVIRI data and NWC SAF cloud mask).

4. Dictionary sounds more flexible.

5. No strict opinion. My use cases are such that I already have the exact files listed. If available, keep it optional.

6. Maybe it'll be more flexible when split.

**Comment by pnuu** [comment]
How about if the file discovery (`discover_scene(platform_name='NOAA-15', start_time=dt.datetime(...), end_time=...)`, or something) function calls the `Scene.__init__()` and returns the created scene? In this way the `Scene` init wouldn't need to be changed in trollflow-sat and the user wouldn't need to have two separate calls.

**Comment by davidh-ssec** [comment]
I think in keeping with the *nix methodology of small single-responsibility tools we should probably have it return filenames. For example, if it returned a Scene that doesn't really allow a user to further filter filenames themselves. Is this a plausible use case, yes. Is it likely, eh probably not.

**Comment by davidh-ssec** [comment]
From discussions on slack:
The best way for this to work would be for the discover function/method should return a dictionary mapping reader names to a list of filenames. This would require the `Scene` to accept this dictionary to make it easy on the user. The easiest solution is to make `Scene(filenames=X)` allow for X to be a dictionary like the above or a list of filenames as usual. The `reader` keyword would also be optional.

Next question is what is the most user-friendly way to make this discover function/method available?

1. Class method on Scene? I vote no since we might as well just create a Scene and return it in this case.
2. Function in `utils`? Maybe make it available `from satpy import discover_function`? I like this one the most.

Names for this method/function:

1. `discover_scene`
2. `discover_files`
3. `discover_filenames`
4. `find_files`
5. `find_scene_files`
6. Other?

**Comment by pnuu** [comment]
My suggestion would be `from satpy import find_files`, `find_files_and_readers`, or something in that line. There could, following my earlier thought, be something like `from satpy import DiscoveryScene` using the separated discovery functionality and returning a Scene based on the search terms. Just for the convenience for the users that often need the discovery feature. Maybe?

**Comment by davidh-ssec** [comment]
I get the appeal of the `DiscoveryScene` object, but I have trouble supporting that as a separate class; especially since it only provides this small additional piece of functionality. A factor function that returns a Scene feels better to me, but still feels "funny".

Would it be too redundant to have the utility function for returning the dictionary and a classmethod on `Scene` that uses the utility and returns a `Scene`?

**Comment by djhoese** [comment]
This was fixed/completed in #91.
