### ISSUE TITLE
Scene(reader, filenames = [radiance, geoloc]) expects filenames to be in a specific format

### ISSUE THREAD

**Issue by AlysonR** [pytroll/satpy#851]
The Scene reader expects the filenames to be in the specific format and if they don't match, it throws a ValueError.

**Comment by djhoese** [comment]
This is intended and is done by design. There is a lot of information we can gain from the filenames and in some cases we need to parse the filename to properly load the data in them. We also typically have to know out of the many files readable by one reader which files were given by the user. Parsing the content of the file to determine this is slow and unreliable.

It is possible to add additional file patterns to help Satpy to match the files for a particular reader. Could you provide some details about what reader you're using and what filenames you would like to work for the reader?

**Comment by AlysonR** [comment]
Ideally it wouldn't require the filename to be in any type of specific format. I'm using the 'modis_l1b' reader.

**Comment by djhoese** [comment]
Ideally, yes, I would agree, but this isn't possible for most satellite instrument formats. It would reduce performance and flexibility of how Satpy can be used if we didn't require file patterns.

Were you able to get your MODIS L1B data read with the modis_l1b reader (I see you made another issue for L2, but what about L1B)?

**Comment by AlysonR** [comment]
Yes I had to fiddle with the filename to match the format you wanted but I got it reading.

**Comment by djhoese** [comment]
Were your files from an official MODIS data provider? If so, it would be a good idea for the file pattern you were using to be added to Satpy as something it recognizes?
