### ISSUE TITLE
For VIIRS composite there are two composites with the same name.

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#973]
In the VIIRS composites I find two composites with the same name: https://github.com/pytroll/satpy/blob/master/satpy/etc/composites/viirs.yaml#L314 and https://github.com/pytroll/satpy/blob/master/satpy/etc/composites/viirs.yaml#L485

Is this expected?

If not, which one is selected?

**Comment by djhoese** [comment]
No it is not expected and I think I talked with @adybbroe about this. Not sure there is a PR to fix it yet.

The `hncc_dnb` is the preferred one in my opinion since raw `DNB` is not really useful without some special scaling/normalization. As for which one is selected, it is most likely random (based on python's internal `dict` ordering).

**Comment by adybbroe** [comment]
This issue is outdated now. I see no duplicate DNB RGBs in the yaml file (checking latest main branch). There are a number of different dnb based recipes but no one is using the same name!
I am closing it.
